version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - "fredclausen"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - "fredclausen"
