name: Deploy to Docker Hub

on:
  # Enable manual running of action if necessary
  workflow_dispatch:
  # Build and deploy the image on pushes to main branch
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.MD'

  # Build and deploy the image nightly (to ensure we pick up any security updates)
  schedule:
    - cron: "0 14 * * *"

jobs:
  deploy_dockerhub_latest:
    name: Deploy Latest to DockerHub
    runs-on: ubuntu-latest

    # Set job-wide environment variables
    #  - REPO: repo name on dockerhub
    #  - IMAGE: image name on dockerhub
    env:
      REPO: fredclausen
      IMAGE: vdlm2dec
      PUSH: true
    steps:

      # Check out our code
      -
        name: Checkout
        uses: actions/checkout@v2

      # Set up QEMU for multi-arch builds
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # Log into docker hub (so we can push images)
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set up buildx for multi platform builds
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # Build "latest"
      -
        name: Build & Push - latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          no-cache: true
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm/v6,linux/arm64
          push: ${{ env.PUSH }}
          tags: ${{ env.REPO }}/${{ env.IMAGE }}:latest

  deploy_dockerhub_latest_nohealthcheck:
    name: Deploy to Latest Noheathcheck DockerHub
    runs-on: ubuntu-latest

    # Set job-wide environment variables
    #  - REPO: repo name on dockerhub
    #  - IMAGE: image name on dockerhub
    env:
      REPO: fredclausen
      IMAGE: acarsdec
      PUSH: true
    steps:

      # Check out our code
      -
        name: Checkout
        uses: actions/checkout@v2

      # Set up QEMU for multi-arch builds
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # Log into docker hub (so we can push images)
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set up buildx for multi platform builds
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # Patch dockerfile to remove healthcheck
      -
        name: Patch Dockerfile to remove healthcheck
        run: sed '/^HEALTHCHECK /d' < Dockerfile > Dockerfile.nohealthcheck

      # Build "latest_nohealthcheck"
      -
        name: Build & Push - latest nohealthcheck
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.nohealthcheck
          no-cache: true
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm/v6,linux/arm64
          push: ${{ env.PUSH }}
          tags: ${{ env.REPO }}/${{ env.IMAGE }}:latest_nohealthcheck

